name: Deploy to Render

on:
  push:
    tags:
      - '*'  # déclenche pour tous les tags

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Deploy render
        run: |
          echo "Déploiement du service..."
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
